FROM python:3.12-alpine

# instalăm Chromium + driver (+ deps minime)
RUN apk add --no-cache \
    chromium \
    chromium-chromedriver \
    chromium-swiftshader \
    libstdc++ \
    musl-utils

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]